// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ijybwfdkiteebytdwhyu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlqeWJ3ZmRraXRlZWJ5dGR3aHl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ2OTk4NDIsImV4cCI6MjA3MDI3NTg0Mn0.vGJD7mzEVpyxzgkLF1Tr4dXFUrRB2vwqH3mffM5TZqo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});